# Generated by Django 4.1.2 on 2024-06-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('celular', models.CharField(max_length=45)),
            ],
        ),
    ]
