# Generated by Django 4.1.2 on 2024-06-29 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo', models.AutoField(db_column='idTipo', primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_produ', models.AutoField(db_column='idProdu', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('foto', models.ImageField(null=True, upload_to='media/')),
                ('stock', models.IntegerField(null=True)),
                ('id_tipo', models.ForeignKey(db_column='idTipo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Atienda.tipoproducto')),
            ],
        ),
    ]
